name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cargo components
        run: |
          rustup component add rustfmt
          rustup component add clippy
          cargo install cargo-machete
          cargo install cargo-audit
      - name: Rust Format
        run: cargo fmt --all -- --check
      - name: Rust Clippy
        run: cargo clippy
      - name: Rust Machete
        run: cargo machete
      - name: Rust Audit
        run: cargo audit
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.2.0
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-targets
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
      - name: Docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
